#ifndef OM_LOG_H
#define OM_LOG_H

#define OPENWILDSTACKS_LOG_CATEGORY "OM"

#define OMINFO  CLOG(INFO, OPENWILDSTACKS_LOG_CATEGORY)
#define OMWARN  CLOG(WARNING, OPENWILDSTACKS_LOG_CATEGORY)
#define OMERROR CLOG(ERROR, OPENWILDSTACKS_LOG_CATEGORY)

//#define OMVLOG1  CVLOG(1, OPENWILDSTACKS_LOG_CATEGORY)
//#define OMVLOG2  CVLOG(2, OPENWILDSTACKS_LOG_CATEGORY)
//#define OMVLOG3  CVLOG(3, OPENWILDSTACKS_LOG_CATEGORY)
//#define OMVLOG4  CVLOG(4, OPENWILDSTACKS_LOG_CATEGORY)

#define OMVLOG1  CLOG(INFO, OPENWILDSTACKS_LOG_CATEGORY)
#define OMVLOG2  CLOG(INFO, OPENWILDSTACKS_LOG_CATEGORY)
#define OMVLOG3  CLOG(INFO, OPENWILDSTACKS_LOG_CATEGORY)
#define OMVLOG4  CLOG(INFO, OPENWILDSTACKS_LOG_CATEGORY)

#define OMINFO_IF(cond)  CLOG_IF(cond, INFO, OPENWILDSTACKS_LOG_CATEGORY)
#define OMWARN_IF(cond)  CLOG_IF(cond, WARNING, OPENWILDSTACKS_LOG_CATEGORY)
#define OMERROR_IF(cond) CLOG_IF(cond, ERROR, OPENWILDSTACKS_LOG_CATEGORY)


#endif // OM_LOG_H  
